#build 
compilacion:	main.o Bombas.o Escenario.o Espina.o Invisible.o Item.o Jugador.o Normal.o Tren.o V.o
	g++ main.o Bombas.o Escenario.o Espina.o Invisible.o Item.o Jugador.o Normal.o Tren.o V.o -o compilacion -lncurses
main.o:	main.cpp Bombas.h Escenario.h Espina.h Invisible.h Item.h Jugador.h Normal.h Tren.h V.h
	g++ -c main.cpp
